[project]
name = "sudoku"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Alexandre Cirilo", email = "38657258+alxdrcirilo@users.noreply.github.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]
